import type { Recipe, InventoryItem, Ingredient, MenuItem, Order, User, Role } from "./types"

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    menu_item_id: 101,
    name: "Classic Margherita Pizza",
    standard_serving_pax: 2,
    accessibility_notes: "High contrast visual instructions available for each step.",
    ingredients: [
      {
        id: 1,
        recipe_id: 1,
        ingredient_id: 1,
        name: "Pizza Dough",
        quantity: "300g",
        quantity_for_recipe: 300,
      },
      {
        id: 2,
        recipe_id: 1,
        ingredient_id: 2,
        name: "Tomato Sauce",
        quantity: "150g",
        quantity_for_recipe: 150,
      },
      {
        id: 3,
        recipe_id: 1,
        ingredient_id: 3,
        name: "Fresh Mozzarella",
        quantity: "200g",
        quantity_for_recipe: 200,
      },
      {
        id: 4,
        recipe_id: 1,
        ingredient_id: 4,
        name: "Fresh Basil Leaves",
        quantity: "10 leaves",
        quantity_for_recipe: 10,
      },
      {
        id: 5,
        recipe_id: 1,
        ingredient_id: 5,
        name: "Olive Oil",
        quantity: "15ml",
        quantity_for_recipe: 15,
      },
    ],
    steps: [
      {
        id: 1,
        recipe_id: 1,
        step_number: 1,
        instruction: "Preheat the oven to 475°F (245°C) with a pizza stone inside if available.",
        image_url: "/placeholder.svg?height=200&width=300",
      },
      {
        id: 2,
        recipe_id: 1,
        step_number: 2,
        instruction: "Roll out the pizza dough on a floured surface to your desired thickness.",
        image_url: "/placeholder.svg?height=200&width=300",
        audio_url: "/audio-instructions.mp3",
      },
      {
        id: 3,
        recipe_id: 1,
        step_number: 3,
        instruction: "Spread the tomato sauce evenly over the dough, leaving a small border for the crust.",
        image_url: "/placeholder.svg?height=200&width=300",
      },
      {
        id: 4,
        recipe_id: 1,
        step_number: 4,
        instruction: "Tear the fresh mozzarella into pieces and distribute evenly over the sauce.",
        image_url: "/placeholder.svg?height=200&width=300",
      },
      {
        id: 5,
        recipe_id: 1,
        step_number: 5,
        instruction:
          "Drizzle with olive oil and bake for 10-12 minutes until the crust is golden and cheese is bubbly.",
        audio_url: "/audio-instructions.mp3",
      },
      {
        id: 6,
        recipe_id: 1,
        step_number: 6,
        instruction: "Remove from oven, top with fresh basil leaves, slice and serve immediately.",
        image_url: "/placeholder.svg?height=200&width=300",
      },
    ],
  },
  {
    id: 2,
    menu_item_id: 102,
    name: "Vegetable Stir Fry",
    standard_serving_pax: 4,
    ingredients: [
      {
        id: 6,
        recipe_id: 2,
        ingredient_id: 6,
        name: "Broccoli Florets",
        quantity: "300g",
        quantity_for_recipe: 300,
      },
      {
        id: 7,
        recipe_id: 2,
        ingredient_id: 7,
        name: "Bell Peppers",
        quantity: "2 medium",
        quantity_for_recipe: 2,
      },
      {
        id: 8,
        recipe_id: 2,
        ingredient_id: 8,
        name: "Carrots",
        quantity: "2 large",
        quantity_for_recipe: 2,
      },
      {
        id: 9,
        recipe_id: 2,
        ingredient_id: 9,
        name: "Soy Sauce",
        quantity: "45ml",
        quantity_for_recipe: 45,
      },
      {
        id: 10,
        recipe_id: 2,
        ingredient_id: 10,
        name: "Sesame Oil",
        quantity: "15ml",
        quantity_for_recipe: 15,
      },
    ],
    steps: [
      {
        id: 7,
        recipe_id: 2,
        step_number: 1,
        instruction: "Wash and chop all vegetables into bite-sized pieces.",
        image_url: "/placeholder.svg?height=200&width=300",
      },
      {
        id: 8,
        recipe_id: 2,
        step_number: 2,
        instruction: "Heat a wok or large frying pan over high heat. Add sesame oil.",
        audio_url: "/audio-instructions.mp3",
      },
      {
        id: 9,
        recipe_id: 2,
        step_number: 3,
        instruction: "Add carrots and stir-fry for 2 minutes.",
        image_url: "/placeholder.svg?height=200&width=300",
      },
      {
        id: 10,
        recipe_id: 2,
        step_number: 4,
        instruction:
          "Add broccoli and bell peppers, stir-fry for another 3-4 minutes until vegetables are crisp-tender.",
        image_url: "/placeholder.svg?height=200&width=300",
      },
      {
        id: 11,
        recipe_id: 2,
        step_number: 5,
        instruction: "Add soy sauce and toss to coat. Serve immediately.",
        audio_url: "/audio-instructions.mp3",
      },
    ],
  },
  {
    id: 3,
    menu_item_id: 103,
    name: "Chocolate Chip Cookies",
    standard_serving_pax: 12,
    accessibility_notes: "Audio instructions available for all steps. High contrast images for visual guidance.",
    ingredients: [
      {
        id: 11,
        recipe_id: 3,
        ingredient_id: 11,
        name: "All-Purpose Flour",
        quantity: "280g",
        quantity_for_recipe: 280,
      },
      {
        id: 12,
        recipe_id: 3,
        ingredient_id: 12,
        name: "Unsalted Butter",
        quantity: "225g",
        quantity_for_recipe: 225,
      },
      {
        id: 13,
        recipe_id: 3,
        ingredient_id: 13,
        name: "Brown Sugar",
        quantity: "200g",
        quantity_for_recipe: 200,
      },
      {
        id: 14,
        recipe_id: 3,
        ingredient_id: 14,
        name: "Granulated Sugar",
        quantity: "100g",
        quantity_for_recipe: 100,
      },
      {
        id: 15,
        recipe_id: 3,
        ingredient_id: 15,
        name: "Eggs",
        quantity: "2 large",
        quantity_for_recipe: 2,
      },
      {
        id: 16,
        recipe_id: 3,
        ingredient_id: 16,
        name: "Chocolate Chips",
        quantity: "300g",
        quantity_for_recipe: 300,
      },
    ],
    steps: [
      {
        id: 12,
        recipe_id: 3,
        step_number: 1,
        instruction: "Preheat oven to 350°F (175°C) and line baking sheets with parchment paper.",
        image_url: "/placeholder.svg?height=200&width=300",
        audio_url: "/audio-instructions.mp3",
      },
      {
        id: 13,
        recipe_id: 3,
        step_number: 2,
        instruction:
          "In a large bowl, cream together the butter, brown sugar, and granulated sugar until light and fluffy.",
        image_url: "/placeholder.svg?height=200&width=300",
        audio_url: "/audio-instructions.mp3",
      },
      {
        id: 14,
        recipe_id: 3,
        step_number: 3,
        instruction: "Beat in eggs one at a time, then stir in vanilla.",
        image_url: "/placeholder.svg?height=200&width=300",
        audio_url: "/audio-instructions.mp3",
      },
      {
        id: 15,
        recipe_id: 3,
        step_number: 4,
        instruction: "Gradually blend in the flour mixture, then fold in chocolate chips.",
        image_url: "/placeholder.svg?height=200&width=300",
        audio_url: "/audio-instructions.mp3",
      },
      {
        id: 16,
        recipe_id: 3,
        step_number: 5,
        instruction: "Drop by rounded tablespoons onto the prepared baking sheets.",
        image_url: "/placeholder.svg?height=200&width=300",
        audio_url: "/audio-instructions.mp3",
      },
      {
        id: 17,
        recipe_id: 3,
        step_number: 6,
        instruction:
          "Bake for 10-12 minutes until edges are golden. Cool on baking sheets for 2 minutes before transferring to wire racks.",
        image_url: "/placeholder.svg?height=200&width=300",
        audio_url: "/audio-instructions.mp3",
      },
    ],
  },
]

export const mockInventory: InventoryItem[] = [
  { id: 1, name: "Pizza Dough", available_quantity: 500, unit: "g" },
  { id: 2, name: "Tomato Sauce", available_quantity: 300, unit: "g" },
  { id: 3, name: "Fresh Mozzarella", available_quantity: 350, unit: "g" },
  { id: 4, name: "Fresh Basil Leaves", available_quantity: 15, unit: "leaves" },
  { id: 5, name: "Olive Oil", available_quantity: 200, unit: "ml" },
  { id: 6, name: "Broccoli Florets", available_quantity: 400, unit: "g" },
  { id: 7, name: "Bell Peppers", available_quantity: 3, unit: "medium" },
  { id: 8, name: "Carrots", available_quantity: 1, unit: "large" }, // Insufficient for recipe
  { id: 9, name: "Soy Sauce", available_quantity: 100, unit: "ml" },
  { id: 10, name: "Sesame Oil", available_quantity: 50, unit: "ml" },
  { id: 11, name: "All-Purpose Flour", available_quantity: 1000, unit: "g" },
  { id: 12, name: "Unsalted Butter", available_quantity: 400, unit: "g" },
  { id: 13, name: "Brown Sugar", available_quantity: 300, unit: "g" },
  { id: 14, name: "Granulated Sugar", available_quantity: 500, unit: "g" },
  { id: 15, name: "Eggs", available_quantity: 6, unit: "large" },
  { id: 16, name: "Chocolate Chips", available_quantity: 200, unit: "g" }, // Insufficient for recipe
]

export const mockIngredients: Ingredient[] = [
  { id: 1, name: "Pizza Dough", quantity: 500, unit: "g", price: 3.99, category: "Grains", location: "Refrigerator" },
  {
    id: 2,
    name: "Tomato Sauce",
    quantity: 300,
    unit: "g",
    price: 2.49,
    category: "Vegetables",
    location: "Dry Storage",
  },
  {
    id: 3,
    name: "Fresh Mozzarella",
    quantity: 350,
    unit: "g",
    price: 4.99,
    category: "Dairy",
    location: "Refrigerator",
  },
  {
    id: 4,
    name: "Fresh Basil Leaves",
    quantity: 15,
    unit: "leaves",
    price: 1.99,
    category: "Herbs",
    location: "Refrigerator",
  },
  { id: 5, name: "Olive Oil", quantity: 200, unit: "ml", price: 8.99, category: "Oils", location: "Dry Storage" },
  {
    id: 6,
    name: "Broccoli Florets",
    quantity: 400,
    unit: "g",
    price: 2.99,
    category: "Vegetables",
    location: "Refrigerator",
  },
  {
    id: 7,
    name: "Bell Peppers",
    quantity: 3,
    unit: "medium",
    price: 1.5,
    category: "Vegetables",
    location: "Refrigerator",
  },
  { id: 8, name: "Carrots", quantity: 1, unit: "large", price: 0.75, category: "Vegetables", location: "Refrigerator" },
  { id: 9, name: "Soy Sauce", quantity: 100, unit: "ml", price: 3.49, category: "Condiments", location: "Dry Storage" },
  { id: 10, name: "Sesame Oil", quantity: 50, unit: "ml", price: 5.99, category: "Oils", location: "Dry Storage" },
  {
    id: 11,
    name: "All-Purpose Flour",
    quantity: 1000,
    unit: "g",
    price: 2.99,
    category: "Grains",
    location: "Dry Storage",
  },
  {
    id: 12,
    name: "Unsalted Butter",
    quantity: 400,
    unit: "g",
    price: 4.49,
    category: "Dairy",
    location: "Refrigerator",
  },
  {
    id: 13,
    name: "Brown Sugar",
    quantity: 300,
    unit: "g",
    price: 2.29,
    category: "Sweeteners",
    location: "Dry Storage",
  },
  {
    id: 14,
    name: "Granulated Sugar",
    quantity: 500,
    unit: "g",
    price: 1.99,
    category: "Sweeteners",
    location: "Dry Storage",
  },
  { id: 15, name: "Eggs", quantity: 6, unit: "large", price: 3.49, category: "Dairy", location: "Refrigerator" },
  {
    id: 16,
    name: "Chocolate Chips",
    quantity: 200,
    unit: "g",
    price: 3.99,
    category: "Baking",
    location: "Dry Storage",
  },
  { id: 17, name: "Salt", quantity: 500, unit: "g", price: 1.29, category: "Spices", location: "Spice Rack" },
  { id: 18, name: "Black Pepper", quantity: 100, unit: "g", price: 2.99, category: "Spices", location: "Spice Rack" },
  { id: 19, name: 'Garlic", quantity:  price: 2.99, category: "Spices', location: "Spice Rack" },
  { id: 19, name: "Garlic", quantity: 8, unit: "cloves", price: 0.99, category: "Vegetables", location: "Dry Storage" },
  { id: 20, name: "Onions", quantity: 5, unit: "medium", price: 1.29, category: "Vegetables", location: "Dry Storage" },
  {
    id: 21,
    name: "Chicken Breast",
    quantity: 1200,
    unit: "g",
    price: 9.99,
    category: "Meat",
    location: "Refrigerator",
  },
  { id: 22, name: "Ground Beef", quantity: 800, unit: "g", price: 7.99, category: "Meat", location: "Refrigerator" },
  { id: 23, name: "Rice", quantity: 2000, unit: "g", price: 4.99, category: "Grains", location: "Dry Storage" },
  { id: 24, name: "Pasta", quantity: 1500, unit: "g", price: 2.49, category: "Grains", location: "Dry Storage" },
]

export const mockMenuItems: MenuItem[] = [
  {
    id: 101,
    name: "Classic Margherita Pizza",
    description: "Traditional Italian pizza with tomato sauce, fresh mozzarella, and basil",
    image_url: "/placeholder.svg?height=300&width=300",
    minimum_order_quantity: 1,
    price: 12.99,
  },
  {
    id: 102,
    name: "Vegetable Stir Fry",
    description: "Fresh vegetables stir-fried with soy sauce and sesame oil",
    image_url: "/placeholder.svg?height=300&width=300",
    minimum_order_quantity: 2,
    price: 9.99,
  },
  {
    id: 103,
    name: "Chocolate Chip Cookies",
    description: "Homemade cookies with chocolate chips",
    image_url: "/placeholder.svg?height=300&width=300",
    minimum_order_quantity: 6,
    price: 1.99,
  },
  {
    id: 104,
    name: "Grilled Chicken Salad",
    description: "Fresh salad with grilled chicken, mixed greens, and house dressing",
    image_url: "/placeholder.svg?height=300&width=300",
    minimum_order_quantity: 1,
    price: 11.99,
  },
  {
    id: 105,
    name: "Beef Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce on a brioche bun",
    image_url: "/placeholder.svg?height=300&width=300",
    minimum_order_quantity: 1,
    price: 13.99,
  },
]

export const mockOrders: Order[] = [
  {
    id: 1001,
    date: "2023-05-15T14:30:00Z",
    customer_name: "John Smith",
    delivery_address: "123 Main St, Anytown, USA",
    delivery_date: "2023-05-16T18:00:00Z",
    kitchen_location: "Main Kitchen",
    items: [
      {
        menu_item_id: 101,
        name: "Classic Margherita Pizza",
        quantity: 2,
        price: 12.99,
      },
      {
        menu_item_id: 103,
        name: "Chocolate Chip Cookies",
        quantity: 12,
        price: 1.99,
      },
    ],
    total: 49.86,
    status: "completed",
  },
  {
    id: 1002,
    date: "2023-05-16T18:45:00Z",
    customer_name: "Sarah Johnson",
    delivery_address: "456 Oak Ave, Somewhere, USA",
    delivery_date: "2023-05-17T12:00:00Z",
    kitchen_location: "Downtown Kitchen",
    items: [
      {
        menu_item_id: 102,
        name: "Vegetable Stir Fry",
        quantity: 3,
        price: 9.99,
      },
      {
        menu_item_id: 104,
        name: "Grilled Chicken Salad",
        quantity: 1,
        price: 11.99,
      },
    ],
    total: 41.96,
    status: "pending",
    notes: "No onions in the stir fry please.",
  },
  {
    id: 1003,
    date: "2023-05-16T12:15:00Z",
    customer_name: "Michael Brown",
    delivery_address: "789 Pine St, Nowhere, USA",
    delivery_date: "2023-05-17T19:00:00Z",
    kitchen_location: "Main Kitchen",
    items: [
      {
        menu_item_id: 105,
        name: "Beef Burger",
        quantity: 4,
        price: 13.99,
      },
      {
        menu_item_id: 103,
        name: "Chocolate Chip Cookies",
        quantity: 24,
        price: 1.99,
      },
    ],
    total: 103.72,
    status: "cancelled",
    notes: "Cancelled due to delivery delay.",
  },
  {
    id: 1004,
    date: "2023-05-17T19:30:00Z",
    customer_name: "Emily Davis",
    delivery_address: "321 Maple Dr, Somewhere, USA",
    delivery_date: "2023-05-18T12:00:00Z",
    kitchen_location: "Downtown Kitchen",
    items: [
      {
        menu_item_id: 101,
        name: "Classic Margherita Pizza",
        quantity: 1,
        price: 12.99,
      },
      {
        menu_item_id: 104,
        name: "Grilled Chicken Salad",
        quantity: 2,
        price: 11.99,
      },
    ],
    total: 36.97,
    status: "pending",
  },
  {
    id: 1005,
    date: "2023-05-17T13:00:00Z",
    customer_name: "David Wilson",
    delivery_address: "654 Elm St, Anytown, USA",
    delivery_date: "2023-05-18T18:00:00Z",
    kitchen_location: "Main Kitchen",
    items: [
      {
        menu_item_id: 102,
        name: "Vegetable Stir Fry",
        quantity: 2,
        price: 9.99,
      },
    ],
    total: 19.98,
    status: "completed",
  },
]

export const mockRoles: Role[] = [
  { id: 1, name: "Admin" },
  { id: 2, name: "Chef" },
  { id: 3, name: "Server" },
]

export const mockUsers: User[] = [
  {
    id: "550e8400-e29b-41d4-a716-446655440000",
    email: "admin@example.com",
    name: "Admin User",
    role_id: 1,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440001",
    email: "chef@example.com",
    name: "Chef User",
    role_id: 2,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440002",
    email: "server@example.com",
    name: "Server User",
    role_id: 3,
  },
]
