-- Create ingredients table if it doesn't exist
CREATE TABLE IF NOT EXISTS ingredients (
  id SERIAL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  quantity NUMERIC NOT NULL CHECK (quantity >= 0),
  threshold_quantity NUMERIC NOT NULL CHECK (threshold_quantity >= 0),
  unit TEXT NOT NULL,
  price NUMERIC,
  category TEXT,
  location TEXT
);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_ingredients_name ON ingredients(name);
CREATE INDEX IF NOT EXISTS idx_ingredients_category ON ingredients(category);
