-- Insert menu items for kitchen management system

INSERT INTO public.menu_items (name, description, image_url, minimum_order_quantity, price) VALUES
('Tomato Pasta', 'Classic pasta with rich tomato sauce', '/images/menu/tomato-pasta.jpg', 1, 12.90),
('Carbonara Pasta', 'Creamy pasta with bacon and parmesan', '/images/menu/carbonara-pasta.jpg', 1, 14.90),
('Mac & Cheese', 'Comfort food macaroni with cheese sauce', '/images/menu/mac-cheese.jpg', 1, 10.90),
('Seasoning for Chicken Katsu', 'Special seasoning blend for chicken katsu', '/images/menu/seasoning.jpg', 1, 2.00),
('Crispy Lemon Chicken Katsu', 'Crispy breaded chicken with lemon flavor', '/images/menu/lemon-chicken-katsu.jpg', 1, 16.90),
('Lemon Sauce', 'Tangy lemon sauce for chicken dishes', '/images/menu/lemon-sauce.jpg', 1, 3.00),
('Sweet & Sour Dory', 'Fish fillet in sweet and sour sauce', '/images/menu/sweet-sour-dory.jpg', 1, 15.90),
('Sweet & Sour Sauce', 'Classic sweet and sour sauce', '/images/menu/sweet-sour-sauce.jpg', 1, 3.50),
('Jasmine Rice', 'Fragrant jasmine rice', '/images/menu/jasmine-rice.jpg', 1, 3.00),
('Butter Chicken', 'Rich and creamy Indian butter chicken', '/images/menu/butter-chicken.jpg', 1, 17.90),
('Spiced Cauliflower with Carrots', 'Aromatic spiced vegetables', '/images/menu/spiced-cauliflower.jpg', 1, 8.90),
('Spiced Basmati Rice', 'Fragrant basmati rice with spices', '/images/menu/spiced-basmati.jpg', 1, 4.50),
('Teriyaki Chicken', 'Japanese-style glazed chicken', '/images/menu/teriyaki-chicken.jpg', 1, 15.90),
('Sweet Thai Chill Roast Chicken', 'Thai-style roasted chicken with sweet chili', '/images/menu/thai-roast-chicken.jpg', 1, 16.90),
('Sweet Thai Chilli Sauce', 'Authentic Thai sweet chili sauce', '/images/menu/thai-chili-sauce.jpg', 1, 3.00),
('Nasi Lemak', 'Malaysian coconut rice with accompaniments', '/images/menu/nasi-lemak.jpg', 1, 13.90),
('Kentucky Chicken Drumlets', 'Crispy fried chicken drumlets', '/images/menu/kentucky-drumlets.jpg', 1, 12.90),
('Nasi Lemak Chilli Paste', 'Spicy sambal for nasi lemak', '/images/menu/nasi-lemak-chili.jpg', 1, 2.50),
('Curry Chicken', 'Traditional curry chicken', '/images/menu/curry-chicken.jpg', 1, 15.90),
('Curry Chicken Sauce', 'Rich curry sauce for chicken', '/images/menu/curry-sauce.jpg', 1, 4.00),
('Black Bean Fish', 'Fish in savory black bean sauce', '/images/menu/black-bean-fish.jpg', 1, 16.90),
('Assam Fish', 'Tangy tamarind fish curry', '/images/menu/assam-fish.jpg', 1, 15.90),
('Assam Paste', 'Tamarind paste for assam dishes', '/images/menu/assam-paste.jpg', 1, 3.50),
('Achar Nanas Timun', 'Pickled pineapple and cucumber salad', '/images/menu/achar.jpg', 1, 6.90),
('Nasi Minak', 'Fragrant coconut rice', '/images/menu/nasi-minak.jpg', 1, 4.50),
('Grilled Lemon Thyme Chicken', 'Herb-crusted grilled chicken', '/images/menu/lemon-thyme-chicken.jpg', 1, 17.90),
('Butter Rice', 'Rich buttery rice', '/images/menu/butter-rice.jpg', 1, 4.00),
('Baby Carrots and Asparagus', 'Fresh steamed vegetables', '/images/menu/baby-carrots-asparagus.jpg', 1, 7.90),
('Steamed Chicken', 'Tender steamed chicken', '/images/menu/steamed-chicken.jpg', 1, 14.90),
('Chicken Rice', 'Hainanese-style chicken rice', '/images/menu/chicken-rice.jpg', 1, 12.90),
('Chicken Rice Chilli Paste', 'Spicy chili sauce for chicken rice', '/images/menu/chicken-rice-chili.jpg', 1, 2.50),
('5 Spices Chicken', 'Aromatic five-spice chicken', '/images/menu/five-spice-chicken.jpg', 1, 15.90),
('Yam Rice', 'Fragrant yam-flavored rice', '/images/menu/yam-rice.jpg', 1, 4.50),
('Chinese Rojak', 'Mixed fruit and vegetable salad', '/images/menu/chinese-rojak.jpg', 1, 8.90),
('Jap Curry Sauce', 'Japanese-style curry sauce', '/images/menu/jap-curry-sauce.jpg', 1, 4.50),
('Jap Curry Chicken', 'Japanese curry with chicken', '/images/menu/jap-curry-chicken.jpg', 1, 16.90),
('Hainanese Chicken Cutlet', 'Crispy chicken cutlet Hainanese style', '/images/menu/hainanese-cutlet.jpg', 1, 15.90),
('Prawn Paste Chicken Drumlets (Har Cheong Gai)', 'Chicken drumlets with prawn paste', '/images/menu/har-cheong-gai.jpg', 1, 14.90),
('Lemon Pepper Dory', 'Fish fillet with lemon pepper seasoning', '/images/menu/lemon-pepper-dory.jpg', 1, 15.90),
('Turmeric Rice', 'Golden turmeric-flavored rice', '/images/menu/turmeric-rice.jpg', 1, 4.00),
('Chicken Rendang', 'Rich Indonesian chicken rendang', '/images/menu/chicken-rendang.jpg', 1, 17.90),
('Sand Ginger Chicken', 'Chicken with aromatic sand ginger', '/images/menu/sand-ginger-chicken.jpg', 1, 16.90),
('Sand Ginger Chicken Dipping Sauce', 'Special dipping sauce for sand ginger chicken', '/images/menu/sand-ginger-sauce.jpg', 1, 3.00),
('Fried Oyster Tempeh', 'Crispy tempeh with oyster sauce', '/images/menu/fried-oyster-tempeh.jpg', 1, 11.90),
('Kecap Manis Glazed Chicken', 'Chicken glazed with sweet soy sauce', '/images/menu/kecap-manis-chicken.jpg', 1, 16.90),
('Baked Tamarind Glazed Tempeh', 'Tempeh with tangy tamarind glaze', '/images/menu/tamarind-tempeh.jpg', 1, 12.90),
('Grilled Honey Chicken Drumlets', 'Sweet honey-glazed chicken drumlets', '/images/menu/honey-drumlets.jpg', 1, 14.90);