-- Merged ingredients migration - combines initial_ingredients.sql, additional_ingredients.sql, and all_missing_ingredients.sql
-- This file contains all unique ingredients without duplicates

INSERT INTO public.ingredients (name, quantity, unit, threshold_quantity, price, category, storage_type, location_id) VALUES
-- Proteins
('Boneless Chicken', 0, 'kg', 5, 0, 'Meat', 'Refrigerated', 1),
('Chicken Leg With Bone', 0, 'kg', 5, 0, 'Meat', 'Refrigerated', 1),
('Chicken Drumlets', 0, 'kg', 10, 0, 'Meat', 'Frozen', 1),
('Dory Fillet', 0, 'kg', 5, 0, 'Seafood', 'Frozen', 1),
('Turkey Bacon', 0, 'kg', 2, 0, 'Meat', 'Refrigerated', 1),
('Tempeh', 0, 'pcs', 10, 0, 'Other', 'Refrigerated', 1),
('Eggs', 0, 'pcs', 30, 0, 'Dairy', 'Refrigerated', 1),

-- Grains & Pasta
('Jasmine Rice', 0, 'kg', 20, 0, 'Grains', 'Dry', 1),
('Basmati Rice', 0, 'kg', 5, 0, 'Grains', 'Dry', 1),
('Spaghetti', 0, 'kg', 5, 0, 'Grains', 'Dry', 1),
('Macaroni', 0, 'kg', 5, 0, 'Grains', 'Dry', 1),

-- Vegetables & Aromatics
('Fresh Ginger', 0, 'kg', 1, 0, 'Vegetables', 'Refrigerated', 1),
('Scallion', 0, 'bunch', 5, 0, 'Vegetables', 'Refrigerated', 1),
('Shallots', 0, 'kg', 1, 0, 'Vegetables', 'Standard', 1),
('Garlic', 0, 'kg', 1, 0, 'Vegetables', 'Standard', 1),
('Galangal', 0, 'kg', 0.5, 0, 'Herbs', 'Refrigerated', 1),
('Lemongrass', 0, 'bunch', 2, 0, 'Herbs', 'Refrigerated', 1),
('Candlenuts', 0, 'kg', 0.5, 0, 'Other', 'Standard', 1),
('Onions', 0, 'kg', 5, 0, 'Vegetables', 'Standard', 1),
('Cherry Tomatoes', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Green Bell Pepper', 0, 'pcs', 10, 0, 'Vegetables', 'Refrigerated', 1),
('Red Bell Pepper', 0, 'pcs', 10, 0, 'Vegetables', 'Refrigerated', 1),
('Yellow Bell Pepper', 0, 'pcs', 10, 0, 'Vegetables', 'Refrigerated', 1),
('Cucumber', 0, 'kg', 3, 0, 'Vegetables', 'Refrigerated', 1),
('Japanese Cucumber', 0, 'pcs', 10, 0, 'Vegetables', 'Refrigerated', 1),
('Carrots', 0, 'kg', 5, 0, 'Vegetables', 'Refrigerated', 1),
('Baby Carrots', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Asparagus', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Zucchini', 0, 'pcs', 5, 0, 'Vegetables', 'Refrigerated', 1),
('Mushrooms', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Shiitake Mushrooms', 0, 'kg', 1, 0, 'Vegetables', 'Dry', 1),
('Bean Sprouts', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Chinese Turnip', 0, 'kg', 3, 0, 'Vegetables', 'Refrigerated', 1),
('Kangkong', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Broccoli', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Green Beans', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Cabbage', 0, 'kg', 3, 0, 'Vegetables', 'Refrigerated', 1),
('Cauliflower', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Potatoes', 0, 'kg', 10, 0, 'Vegetables', 'Standard', 1),
('Taro', 0, 'kg', 5, 0, 'Vegetables', 'Standard', 1),
('Small Shallots', 0, 'kg', 1, 0, 'Vegetables', 'Standard', 1),

-- Fruits
('Pineapple', 0, 'pcs', 5, 0, 'Fruits', 'Refrigerated', 1),
('Canned Pineapple', 0, 'pcs', 10, 0, 'Fruits', 'Canned', 1),
('Apple', 0, 'kg', 3, 0, 'Fruits', 'Refrigerated', 1),
('Lemon', 0, 'pcs', 10, 0, 'Fruits', 'Refrigerated', 1),
('Golden Raisins', 0, 'kg', 1, 0, 'Fruits', 'Standard', 1),
('Sultanas', 0, 'kg', 1, 0, 'Fruits', 'Standard', 1),
('Pineapple Syrup', 0, 'pcs', 10, 0, 'Fruits', 'Canned', 1),

-- Dairy & Fats
('Unsalted Butter', 0, 'kg', 2, 0, 'Dairy', 'Refrigerated', 1),
('Cream Cheese', 0, 'kg', 1, 0, 'Dairy', 'Refrigerated', 1),
('Mozzarella Cheese', 0, 'kg', 2, 0, 'Dairy', 'Refrigerated', 1),
('Cheddar Cheese', 0, 'kg', 2, 0, 'Dairy', 'Refrigerated', 1),
('Parmesan Cheese', 0, 'kg', 1, 0, 'Dairy', 'Refrigerated', 1),
('UHT Milk', 0, 'l', 10, 0, 'Dairy', 'Standard', 1),
('Evaporated Milk', 0, 'l', 5, 0, 'Dairy', 'Standard', 1),
('Heavy Cream', 0, 'l', 3, 0, 'Dairy', 'Refrigerated', 1),
('Greek Yogurt', 0, 'kg', 2, 0, 'Dairy', 'Refrigerated', 1),
('Coconut Cream', 0, 'l', 5, 0, 'Other', 'Standard', 1),
('Coconut Milk', 0, 'l', 5, 0, 'Other', 'Standard', 1),
('Coconut Powder Milk', 0, 'kg', 2, 0, 'Other', 'Standard', 1),
('Ghee', 0, 'kg', 1, 0, 'Oils', 'Standard', 1),

-- Oils
('Vegetable Oil', 0, 'l', 5, 0, 'Oils', 'Standard', 1),
('Cooking Oil', 0, 'l', 10, 0, 'Oils', 'Standard', 1),
('Olive Oil', 0, 'l', 3, 0, 'Oils', 'Standard', 1),
('Sesame Oil', 0, 'l', 1, 0, 'Oils', 'Standard', 1),
('Chicken Oil', 0, 'l', 2, 0, 'Oils', 'Refrigerated', 1),
('Chicken Drippings', 0, 'l', 1, 0, 'Oils', 'Refrigerated', 1),

-- Sauces & Pastes
('Light Soy Sauce', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Dark Soy Sauce', 0, 'l', 1, 0, 'Other', 'Standard', 1),
('Vegetarian Oyster Sauce', 0, 'l', 1, 0, 'Other', 'Standard', 1),
('Kecap Manis', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Dolmio Tomato Pasta Sauce', 0, 'pcs', 10, 0, 'Other', 'Standard', 1),
('Tomato Paste', 0, 'kg', 2, 0, 'Other', 'Standard', 1),
('Sweet Thai Chilli Sauce', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Teriyaki Sauce', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Thai Fish Sauce', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Fermented Black Bean Sauce', 0, 'l', 1, 0, 'Other', 'Standard', 1),
('Rendang Paste', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Teans Gourmet Rendang Paste', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Fermented Prawn Paste', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Black Prawn Paste', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Singlong Chicken Rice Chilli', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Ketchup', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Ginger Garlic Paste', 0, 'kg', 1, 0, 'Other', 'Refrigerated', 1),

-- Spices & Seasonings
('Sand Ginger Powder', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Sea Salt', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Fine Sea Salt', 0, 'g', 2, 0, 'Spices', 'Dry', 1),
('White Pepper', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Black Pepper', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Turmeric Powder', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Five Spice Powder', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Italian Seasoning', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Chicken Seasoning', 0, 'g', 2, 0, 'Spices', 'Dry', 1),
('Kentucky Chicken Seasoning', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Lemon Pepper Seasoning', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Mustard Seeds', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Cumin Seeds', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Cardamom', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Cloves', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Star Anise', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Bay Leaf', 0, 'g', 0.5, 0, 'Herbs', 'Dry', 1),
('Bay Leaves', 0, 'g', 0.2, 0, 'Herbs', 'Dry', 1),
('Baba Curry Powder', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Baba Meat Curry Powder', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Coriander Powder', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Cumin Powder', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Garam Masala', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Ajinomoto', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Garlic Powder', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Onion Powder', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Singlong Sambal Chilli', 0, 'g', 3, 0, 'Spices', 'Standard', 1),
('Sambal', 0, 'g', 1, 0, 'Spices', 'Standard', 1),
('Saffron Threads', 0, 'g', 0.1, 0, 'Spices', 'Dry', 1),
('Generous Pinch Saffron', 0, 'g', 0.05, 0, 'Spices', 'Dry', 1),
('Dried Chilies', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Dried Chili Paste', 0, 'g', 1, 0, 'Spices', 'Standard', 1),
('Butter Chicken Seasoning', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Knorr Lime Powder', 0, 'g', 0.5, 0, 'Spices', 'Dry', 1),
('Chicken Stock Powder', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Hao Chi Seasoning', 0, 'g', 1, 0, 'Spices', 'Dry', 1),
('Whole Spice Mix', 0, 'g', 1, 0, 'Spices', 'Dry', 1),

-- Herbs & Leaves
('Mixed Herbs', 0, 'kg', 0.5, 0, 'Herbs', 'Dry', 1),
('Oregano', 0, 'kg', 0.5, 0, 'Herbs', 'Dry', 1),
('Thyme', 0, 'kg', 0.5, 0, 'Herbs', 'Dry', 1),
('Pandan Leaves', 0, 'bunch', 5, 0, 'Herbs', 'Refrigerated', 1),
('Curry Leaves', 0, 'bunch', 3, 0, 'Herbs', 'Refrigerated', 1),
('Coriander Leaves', 0, 'bunch', 5, 0, 'Herbs', 'Refrigerated', 1),
('Green Onion', 0, 'bunch', 5, 0, 'Vegetables', 'Refrigerated', 1),
('Lime Leaves', 0, 'bunch', 2, 0, 'Herbs', 'Refrigerated', 1),

-- Sweeteners
('Sugar', 0, 'kg', 2, 0, 'Sweeteners', 'Dry', 1),
('Palm Sugar', 0, 'kg', 1, 0, 'Sweeteners', 'Dry', 1),
('Brown Sugar', 0, 'kg', 1, 0, 'Sweeteners', 'Dry', 1),
('Honey', 0, 'kg', 1, 0, 'Sweeteners', 'Standard', 1),
('Light Flavoured Honey', 0, 'kg', 2, 0, 'Sweeteners', 'Standard', 1),
('Gula Melaka', 0, 'kg', 2, 0, 'Sweeteners', 'Standard', 1),

-- Liquids & Stocks
('Chicken Stock', 0, 'l', 2, 0, 'Other', 'Refrigerated', 1),
('Chicken Broth', 0, 'l', 5, 0, 'Other', 'Refrigerated', 1),
('Lime Juice', 0, 'l', 1, 0, 'Other', 'Refrigerated', 1),
('Tamarind Water', 0, 'l', 1, 0, 'Other', 'Standard', 1),
('Assam Java', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Vinegar', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Ice', 0, 'kg', 20, 0, 'Other', 'Frozen', 1),
('Mushroom Soaking Liquid', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Tamarind', 0, 'l', 1, 0, 'Other', 'Standard', 1),

-- Baking & Flours
('Tapioca Flour', 0, 'kg', 2, 0, 'Baking', 'Dry', 1),
('Plain Flour', 0, 'kg', 5, 0, 'Baking', 'Dry', 1),
('Potato Starch', 0, 'kg', 1, 0, 'Baking', 'Dry', 1),
('Bread Crumbs', 0, 'kg', 2, 0, 'Baking', 'Dry', 1),

-- Nuts & Seeds
('Cashew Nuts', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Almonds', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Sesame Seeds', 0, 'kg', 0.5, 0, 'Other', 'Standard', 1),

-- Specialty Items
('Fresh Long Chili', 0, 'kg', 1, 0, 'Vegetables', 'Refrigerated', 1),
('Fermented Black Beans', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Coconut', 0, 'kg', 2, 0, 'Other', 'Frozen', 1),
('Bean Curd', 0, 'pcs', 20, 0, 'Other', 'Refrigerated', 1),
('Japanese Curry Block', 0, 'kg', 2, 0, 'Other', 'Standard', 1),
('Shallots', 0, 'kg', 1, 0, 'Other', 'Standard', 1),

-- Kitchen Supplies
('Aluminum Foil', 0, 'pcs', 5, 0, 'Other', 'Standard', 1),
('Baking Sheet', 0, 'pcs', 3, 0, 'Other', 'Standard', 1),
('Kitchen Paper', 0, 'pcs', 10, 0, 'Other', 'Standard', 1),
