-- Insert menu items for kitchen management system

INSERT INTO public.menu_items (name, description, image_url, minimum_order_quantity, price) VALUES
('Tomato Pasta', 'Classic pasta with rich tomato sauce', null, 1, 12.90),
('Carbonara Pasta', 'Creamy pasta with bacon and parmesan', null, 1, 14.90),
('Mac & Cheese', 'Comfort food macaroni with cheese sauce', null, 1, 10.90),
('Seasoning for Chicken Katsu', 'Special seasoning blend for chicken katsu', null, 1, 2.00),
('Crispy Lemon Chicken Katsu', 'Crispy breaded chicken with lemon flavor', null, 1, 16.90),
('Lemon Sauce', 'Tangy lemon sauce for chicken dishes', null, 1, 3.00),
('Sweet & Sour Dory', 'Fish fillet in sweet and sour sauce', null, 1, 15.90),
('Sweet & Sour Sauce', 'Classic sweet and sour sauce', null, 1, 3.50),
('Jasmine Rice', 'Fragrant jasmine rice', null, 1, 3.00),
('Butter Chicken', 'Rich and creamy Indian butter chicken', null, 1, 17.90),
('Spiced Cauliflower with Carrots', 'Aromatic spiced vegetables', null, 1, 8.90),
('Spiced Basmati Rice', 'Fragrant basmati rice with spices', null, 1, 4.50),
('Teriyaki Chicken', 'Japanese-style glazed chicken', null, 1, 15.90),
('Sweet Thai Chill Roast Chicken', 'Thai-style roasted chicken with sweet chili', null, 1, 16.90),
('Sweet Thai Chilli Sauce', 'Authentic Thai sweet chili sauce', null, 1, 3.00),
('Nasi Lemak', 'Malaysian coconut rice with accompaniments', null, 1, 13.90),
('Kentucky Chicken Drumlets', 'Crispy fried chicken drumlets', null, 1, 12.90),
('Nasi Lemak Chilli Paste', 'Spicy sambal for nasi lemak', null, 1, 2.50),
('Curry Chicken', 'Traditional curry chicken', null, 1, 15.90),
('Curry Chicken Sauce', 'Rich curry sauce for chicken', null, 1, 4.00),
('Black Bean Fish', 'Fish in savory black bean sauce', null, 1, 16.90),
('Assam Fish', 'Tangy tamarind fish curry', null, 1, 15.90),
('Assam Paste', 'Tamarind paste for assam dishes', null, 1, 3.50),
('Achar Nanas Timun', 'Pickled pineapple and cucumber salad', null, 1, 6.90),
('Nasi Minak', 'Fragrant coconut rice', null, 1, 4.50),
('Grilled Lemon Thyme Chicken', 'Herb-crusted grilled chicken', null, 1, 17.90),
('Butter Rice', 'Rich buttery rice', null, 1, 4.00),
('Baby Carrots and Asparagus', 'Fresh steamed vegetables', null, 1, 7.90),
('Steamed Chicken', 'Tender steamed chicken', null, 1, 14.90),
('Chicken Rice', 'Hainanese-style chicken rice', null, 1, 12.90),
('Chicken Rice Chilli Paste', 'Spicy chili sauce for chicken rice', null, 1, 2.50),
('5 Spices Chicken', 'Aromatic five-spice chicken', null, 1, 15.90),
('Yam Rice', 'Fragrant yam-flavored rice', null, 1, 4.50),
('Chinese Rojak', 'Mixed fruit and vegetable salad', null, 1, 8.90),
('Jap Curry Sauce', 'Japanese-style curry sauce', null, 1, 4.50),
('Jap Curry Chicken', 'Japanese curry with chicken', null, 1, 16.90),
('Hainanese Chicken Cutlet', 'Crispy chicken cutlet Hainanese style', null, 1, 15.90),
('Prawn Paste Chicken Drumlets (Har Cheong Gai)', 'Chicken drumlets with prawn paste', null, 1, 14.90),
('Lemon Pepper Dory', 'Fish fillet with lemon pepper seasoning', null, 1, 15.90),
('Turmeric Rice', 'Golden turmeric-flavored rice', null, 1, 4.00),
('Chicken Rendang', 'Rich Indonesian chicken rendang', null, 1, 17.90),
('Sand Ginger Chicken', 'Chicken with aromatic sand ginger', null, 1, 16.90),
('Sand Ginger Chicken Dipping Sauce', 'Special dipping sauce for sand ginger chicken', null, 1, 3.00),
('Fried Oyster Tempeh', 'Crispy tempeh with oyster sauce', null, 1, 11.90),
('Kecap Manis Glazed Chicken', 'Chicken glazed with sweet soy sauce', null, 1, 16.90),
('Baked Tamarind Glazed Tempeh', 'Tempeh with tangy tamarind glaze', null, 1, 12.90),
('Grilled Honey Chicken Drumlets', 'Sweet honey-glazed chicken drumlets', null, 1, 14.90);