-- Insert additional ingredients for kitchen management system

INSERT INTO public.ingredients (name, quantity, unit, threshold_quantity, price, category, storage_type, location_id) VALUES
-- Proteins
('Chicken Leg With Bone', 0, 'kg', 5, 0, 'Meat', 'Refrigerated', 1),
('Frozen Chicken Drumlets', 0, 'kg', 10, 0, 'Meat', 'Frozen', 1),
('Dory Fillet', 0, 'kg', 5, 0, 'Seafood', 'Frozen', 1),
('Turkey Bacon', 0, 'kg', 2, 0, 'Meat', 'Refrigerated', 1),
('Eggs', 0, 'pcs', 30, 0, 'Dairy', 'Refrigerated', 1),

-- Grains & Pasta
('Jasmine Rice', 0, 'kg', 20, 0, 'Grains', 'Dry', 1),
('Basmati Rice', 0, 'kg', 5, 0, 'Grains', 'Dry', 1),
('Spaghetti', 0, 'kg', 5, 0, 'Grains', 'Dry', 1),
('Macaroni', 0, 'kg', 5, 0, 'Grains', 'Dry', 1),

-- Vegetables & Aromatics
('Onions', 0, 'kg', 5, 0, 'Vegetables', 'Standard', 1),
('Cherry Tomatoes', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Green Bell Pepper', 0, 'pcs', 10, 0, 'Vegetables', 'Refrigerated', 1),
('Red Bell Pepper', 0, 'pcs', 10, 0, 'Vegetables', 'Refrigerated', 1),
('Yellow Bell Pepper', 0, 'pcs', 10, 0, 'Vegetables', 'Refrigerated', 1),
('Cucumber', 0, 'kg', 3, 0, 'Vegetables', 'Refrigerated', 1),
('Japanese Cucumber', 0, 'pcs', 10, 0, 'Vegetables', 'Refrigerated', 1),
('Carrots', 0, 'kg', 5, 0, 'Vegetables', 'Refrigerated', 1),
('Baby Carrots', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Asparagus', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Zucchini', 0, 'pcs', 5, 0, 'Vegetables', 'Refrigerated', 1),
('Mushrooms', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Dried Shiitake Mushrooms', 0, 'kg', 1, 0, 'Vegetables', 'Dry', 1),
('Bean Sprouts', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Chinese Turnip', 0, 'kg', 3, 0, 'Vegetables', 'Refrigerated', 1),
('Kangkong', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Broccoli', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Green Beans', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Cabbage', 0, 'kg', 3, 0, 'Vegetables', 'Refrigerated', 1),
('Cauliflower', 0, 'kg', 2, 0, 'Vegetables', 'Refrigerated', 1),
('Potatoes', 0, 'kg', 10, 0, 'Vegetables', 'Standard', 1),
('Taro', 0, 'kg', 5, 0, 'Vegetables', 'Standard', 1),
('Pineapple', 0, 'pcs', 5, 0, 'Fruits', 'Refrigerated', 1),
('Canned Pineapple', 0, 'pcs', 10, 0, 'Fruits', 'Canned', 1),
('Apple', 0, 'kg', 3, 0, 'Fruits', 'Refrigerated', 1),

-- Dairy & Fats
('Unsalted Butter', 0, 'kg', 2, 0, 'Dairy', 'Refrigerated', 1),
('Cream Cheese', 0, 'kg', 1, 0, 'Dairy', 'Refrigerated', 1),
('Mozzarella Cheese', 0, 'kg', 2, 0, 'Dairy', 'Refrigerated', 1),
('Cheddar Cheese', 0, 'kg', 2, 0, 'Dairy', 'Refrigerated', 1),
('Parmesan Cheese', 0, 'kg', 1, 0, 'Dairy', 'Refrigerated', 1),
('UHT Milk', 0, 'l', 10, 0, 'Dairy', 'Standard', 1),
('Evaporated Milk', 0, 'l', 5, 0, 'Dairy', 'Standard', 1),
('Heavy Cream', 0, 'l', 3, 0, 'Dairy', 'Refrigerated', 1),
('Greek Yogurt', 0, 'kg', 2, 0, 'Dairy', 'Refrigerated', 1),
('Coconut Cream', 0, 'l', 5, 0, 'Other', 'Standard', 1),
('Coconut Milk', 0, 'l', 5, 0, 'Other', 'Standard', 1),
('Ghee', 0, 'kg', 1, 0, 'Oils', 'Standard', 1),

-- Oils & Condiments
('Cooking Oil', 0, 'l', 10, 0, 'Oils', 'Standard', 1),
('Olive Oil', 0, 'l', 3, 0, 'Oils', 'Standard', 1),

-- Sauces & Pastes
('Dolmio Tomato Pasta Sauce', 0, 'pcs', 10, 0, 'Other', 'Standard', 1),
('Tomato Paste', 0, 'kg', 2, 0, 'Other', 'Standard', 1),
('Sweet Thai Chilli Sauce', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Teriyaki Sauce', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Thai Fish Sauce', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Fermented Black Bean Sauce', 0, 'l', 1, 0, 'Other', 'Standard', 1),
('Singlong Sambal Chilli', 0, 'kg', 3, 0, 'Spices', 'Standard', 1),
('Rendang Paste', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Fermented Prawn Paste', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Black Prawn Paste', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Singlong Chicken Rice Chilli', 0, 'kg', 1, 0, 'Other', 'Standard', 1),

-- Spices & Seasonings
('Italian Seasoning', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Mixed Herbs', 0, 'kg', 0.5, 0, 'Herbs', 'Dry', 1),
('Chicken Seasoning', 0, 'kg', 2, 0, 'Spices', 'Dry', 1),
('Kentucky Chicken Seasoning', 0, 'kg', 1, 0, 'Spices', 'Dry', 1),
('Lemon Pepper Seasoning', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Oregano', 0, 'kg', 0.5, 0, 'Herbs', 'Dry', 1),
('Thyme', 0, 'kg', 0.5, 0, 'Herbs', 'Dry', 1),
('Mustard Seeds', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Cumin Seeds', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Cardamom', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Cinnamon Stick', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Cloves', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Star Anise', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Bay Leaf', 0, 'kg', 0.5, 0, 'Herbs', 'Dry', 1),
('Baba Curry Powder', 0, 'kg', 1, 0, 'Spices', 'Dry', 1),
('Baba Meat Curry Powder', 0, 'kg', 1, 0, 'Spices', 'Dry', 1),
('Coriander Powder', 0, 'kg', 1, 0, 'Spices', 'Dry', 1),
('Cumin Powder', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Garam Masala', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Ajinomoto', 0, 'kg', 1, 0, 'Spices', 'Dry', 1),
('Garlic Powder', 0, 'kg', 1, 0, 'Spices', 'Dry', 1),
('Onion Powder', 0, 'kg', 1, 0, 'Spices', 'Dry', 1),

-- Herbs & Leaves
('Pandan Leaves', 0, 'bunch', 5, 0, 'Herbs', 'Refrigerated', 1),
('Curry Leaves', 0, 'bunch', 3, 0, 'Herbs', 'Refrigerated', 1),
('Coriander Leaves', 0, 'bunch', 5, 0, 'Herbs', 'Refrigerated', 1),
('Green Onion', 0, 'bunch', 5, 0, 'Vegetables', 'Refrigerated', 1),

-- Liquids & Others
('Chicken Broth', 0, 'l', 5, 0, 'Other', 'Refrigerated', 1),
('Assam Java', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Vinegar', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Raw Cashews', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Roasted White Sesame Seeds', 0, 'kg', 0.5, 0, 'Other', 'Standard', 1),
('Golden Raisins', 0, 'kg', 1, 0, 'Fruits', 'Standard', 1),
('Saffron Threads', 0, 'kg', 0.1, 0, 'Spices', 'Dry', 1),
('Dried Chilies', 0, 'kg', 1, 0, 'Spices', 'Dry', 1),
('Fresh Long Chili', 0, 'kg', 1, 0, 'Vegetables', 'Refrigerated', 1),
('Tapioca Flour', 0, 'kg', 2, 0, 'Baking', 'Dry', 1),
('Plain Flour', 0, 'kg', 5, 0, 'Baking', 'Dry', 1),
('Potato Starch', 0, 'kg', 1, 0, 'Baking', 'Dry', 1),
('Bread Crumbs', 0, 'kg', 2, 0, 'Baking', 'Dry', 1),
('Fermented Black Beans', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Grated Coconut', 0, 'kg', 2, 0, 'Other', 'Frozen', 1),
('Toasted Grated Coconut', 0, 'kg', 1, 0, 'Other', 'Standard', 1),
('Fried Bean Curd', 0, 'pcs', 20, 0, 'Other', 'Refrigerated', 1),
('Japanese Curry Block', 0, 'kg', 2, 0, 'Other', 'Standard', 1),
('Ketchup', 0, 'l', 2, 0, 'Other', 'Standard', 1),
('Lemon', 0, 'pcs', 10, 0, 'Fruits', 'Refrigerated', 1),
('Gula Melaka', 0, 'kg', 2, 0, 'Sweeteners', 'Standard', 1),
('Ginger Garlic Paste', 0, 'kg', 1, 0, 'Other', 'Refrigerated', 1),
('Butter Chicken Seasoning', 0, 'kg', 1, 0, 'Spices', 'Dry', 1),
('Knorr Lime Powder', 0, 'kg', 0.5, 0, 'Spices', 'Dry', 1),
('Dried Chili Paste', 0, 'kg', 1, 0, 'Spices', 'Standard', 1),
('Fried Shallots', 0, 'kg', 1, 0, 'Other', 'Standard', 1);